title: CCG Lab Pages
description: A collection of lab resources for the Center for Comparative Genomics at the California Academy of Sciences
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  CAS Intranet: https://sites.google.com/calacademy.org/intranet/
  GH Pages Repository: https://github.com/CCG-CAS/gh-pages
